apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo2
  namespace: default
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: demo2
  template:
    metadata:
      labels:
        app: demo2
    spec:
      containers:
        - name: demo2
          image: your-registry/demo2:latest  # 최신 이미지 사용
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: demo2
  namespace: default
spec:
  selector:
    app: demo2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP  # ALB Ingress Controller와 연동 가능하도록 설정
